# Generated by Django 3.1.7 on 2021-12-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employeerole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_date', models.DateField()),
                ('role_description', models.CharField(choices=[('Cashier', 'Cashier'), ('Preparation', 'Preparation'), ('Cleaning', 'Cleaning')], max_length=20)),
                ('is_manager', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'employeerole',
                'managed': False,
            },
        ),
    ]
