# Generated by Django 4.0 on 2021-12-15 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseFlavor',
            fields=[
                ('bf_id', models.AutoField(primary_key=True, serialize=False)),
                ('bf_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'base_flavor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredient_id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredient_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('price_per_serving', models.FloatField()),
                ('replenished_stock', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], max_length=1)),
            ],
            options={
                'db_table': 'ingredient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('io_quantity', models.IntegerField()),
                ('total_sales', models.FloatField()),
            ],
            options={
                'db_table': 'item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('size_id', models.AutoField(primary_key=True, serialize=False)),
                ('serv_size', models.CharField(choices=[('8', '8'), ('12', '12'), ('16', '16')], max_length=2)),
            ],
            options={
                'db_table': 'size',
                'managed': False,
            },
        ),
    ]
