# Generated by Django 3.1.7 on 2021-12-15 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_baseflavor_customer_ingredient_item_orders_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'managed': False, 'verbose_name_plural': 'Orders'},
        ),
    ]
